CREATE DATABASE DatVeXeKhach
GO
USE DatVeXeKhach
GO

---Table
--Khách hàng
CREATE TABLE KhachHang
(
	Sdt VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(100)
)
GO
-- Xe
CREATE TABLE Xe
(
	BienSo VARCHAR(10) PRIMARY KEY,
	TenXe NVARCHAR(50) NOT NULL,
	SoChoNgoi INT NOT NULL DEFAULT 30,
	TinhTrang INT NOT NULL DEFAULT 0
)
GO


--Lịch trình
CREATE TABLE LichTrinh
(
	MaLT INT IDENTITY(102,1) PRIMARY KEY,
	BienSo VARCHAR(10) NOT NULL,
	GioDi TIME NOT NULL,
	NgayDi DATE NOT NULL,
	DiemDi NVARCHAR(50),
	DiemDen NVARCHAR(50),
	GiaTien MONEY NOT NULL,
	TrangThai INT NOT NULL DEFAULT 0,
	FOREIGN KEY (BienSo) REFERENCES dbo.Xe(BienSo)
)
GO



CREATE TABLE Ve
(
	MaVe INT IDENTITY(1, 1) PRIMARY KEY,
	MaLT INT NOT NULL,
	MaGhe VARCHAR(3),
	Sdt VARCHAR(10),
	TrangThai INT NOT NULL DEFAULT 0,
	GioDi VARCHAR(5),
	GiaVe MONEY DEFAULT 0,
	FOREIGN KEY (MaLT) REFERENCES dbo.LichTrinh(MaLT), 
	FOREIGN KEY (Sdt) REFERENCES dbo.KhachHang(Sdt)
)
GO

