//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenDi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenDi()
        {
            this.DatVeXes = new HashSet<DatVeXe>();
            this.ThongTinVeXes = new HashSet<ThongTinVeXe>();
        }
    
        public int maCD { get; set; }
        public string gioDi { get; set; }
        public System.DateTime ngayDi { get; set; }
        public string diemDi { get; set; }
        public string diemDen { get; set; }
        public double giaVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatVeXe> DatVeXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinVeXe> ThongTinVeXes { get; set; }
    }
}
