//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatVeXe
    {
        public int soDienThoai { get; set; }
        public int maCD { get; set; }
        public string maGhe { get; set; }
        public System.DateTime thoiGianDat { get; set; }
    
        public virtual ChuyenDi ChuyenDi { get; set; }
        public virtual HanhKhach HanhKhach { get; set; }
    }
}
