//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongNV
    {
        public string maBen { get; set; }
        public string maNV { get; set; }
        public Nullable<System.DateTime> ngayVaoLam { get; set; }
        public Nullable<double> Luong { get; set; }
    
        public virtual BenXe BenXe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
