//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianHoatDong
    {
        public string bienSo { get; set; }
        public string maBen { get; set; }
        public Nullable<System.DateTime> ngayKyHopDong { get; set; }
        public string loaiXe { get; set; }
        public Nullable<double> chietKhau { get; set; }
    
        public virtual BenXe BenXe { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
