//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinVeXe
    {
        public string bienSo { get; set; }
        public int maCD { get; set; }
        public Nullable<int> soLuongVe { get; set; }
    
        public virtual ChuyenDi ChuyenDi { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
