//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int MaVe { get; set; }
        public int MaLT { get; set; }
        public string MaGhe { get; set; }
        public string Sdt { get; set; }
        public int TrangThai { get; set; }
        public string GioDi { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual LichTrinh LichTrinh { get; set; }
    }
}
