//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiuaKy_AppDatVeXe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanVeXeKhachEntities : DbContext
    {
        public QuanLyBanVeXeKhachEntities()
            : base("name=QuanLyBanVeXeKhachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenXe> BenXes { get; set; }
        public virtual DbSet<ChuyenDi> ChuyenDis { get; set; }
        public virtual DbSet<DatVeXe> DatVeXes { get; set; }
        public virtual DbSet<HanhKhach> HanhKhaches { get; set; }
        public virtual DbSet<HopDongNV> HopDongNVs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThoiGianHoatDong> ThoiGianHoatDongs { get; set; }
        public virtual DbSet<ThongTinVeXe> ThongTinVeXes { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    }
}
